.PHONY : convert

convert : get-resources
	python3 ./adapters/convert_ATT_NODE_COORD_SECTION.py
	python3 ./adapters/convert_CEIL2D_NODE_COOR_SECTION.py
	python3 ./adapters/convert_EUC2D_NODE_COOR_SECTION.py
	python3 ./adapters/convert_EXPLICIT_FULL_MATRIX.py
	python3 ./adapters/convert_EXPLICIT_LOWER_DIAG_ROW.py
	python3 ./adapters/convert_EXPLICIT_UPPER_DIAG_ROW.py
	python3 ./adapters/convert_EXPLICIT_UPPER_ROW.py
	python3 ./adapters/convert_GEO_COORD_DISPLAY_NODE_COOR_SECTION.py
